/*
 * Copyright 2014 Philip Cronje
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/**
 * Utility class defining static methods to interact with POM files generated by the {@code
 * maven-publish} plugin.
 */
abstract class PomUtils {

	/**
	 * Fixes dependencies that would otherwise be added to the POM with a scope value of {@code
	 * runtime}, which should actually be {@code compile}.
	 *
	 * @param pom the object returned by {@code pom.withXml}
	 * @param configurations the configurations property of the project
	 */
	static void fixCompileDependencies(pom, configurations) {

		def dependencies = pom.asNode().dependencies.'*'.findAll() {
			it.scope.text() == 'runtime' && configurations.compile.allDependencies.find {
				dep -> dep.name == it.artifactId.text()
			}
		}
		dependencies.each { it.scope*.value = 'compile' }
	}
}
